### PR TITLE
Fix cli compile issue

### PR DESCRIPTION
**Pull request by LeoZhang-ATMEL**
This pull request only fix metadata issues, to make build pipeline pass.
The code generated for project is same as previous version.

### CODE REVIEW

**Comment by LeoZhang-ATMEL** [comment]
hi @hurricaneFromMoscow , @wbranski , please help check and merge this PR.
The build pipeline had already passed with this patch.
Thanks

**Comment by wbranski** [comment]
Hi Leo

Thank you for the fix.
I am sorry but I will not be able to check this path today.
First term is on monday next week.

Regards
Wojtek Branski


------------------------------------------------------------------------
*From:* Leozhang-atmel
*Sent:* Friday, July 01, 2016 2:07PM
*To:* Atmelcorp/proximetry-cloud-agent
*Cc:* Wbranski, Mention
*Subject:* Re: [atmelcorp/proximetry-cloud-agent] Fix cli compile issue 
(#5)

hi @hurricaneFromMoscow <https://github.com/hurricaneFromMoscow> , 
@wbranski <https://github.com/wbranski> , please help check and merge 
this PR.
The build pipeline had already passed with this patch.
Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/atmelcorp/proximetry-cloud-agent/pull/5#issuecomment-229930279>, 
or mute the thread 
<https://github.com/notifications/unsubscribe/ARf4fYKWLtEoXrPhiAYEOm6COG6H0WzMks5qRQL1gaJpZM4JDFI->.

**Comment by LeoZhang-ATMEL** [comment]
It's OK, thanks.

**Comment by hurricaneFromMoscow** [comment]
Fine for me

**Comment by LeoZhang-ATMEL** [comment]
Hi Wojtek
Thanks a lot, and please help to merge this Pull Request.

**Pull request closed without merging**
