### PR TITLE
Bugfix/acme 6831 fix middlware missing configuration

### PR DESCRIPTION
**Pull request by LeoZhang-ATMEL**
Remove stdio and temperature sensor init code, since the middleware already been init in system_init().

### CODE REVIEW

**Comment by LeoZhang-ATMEL** [comment]
hi @hurricaneFromMoscow, please help review and merge.
Thanks.

**Comment by hurricaneFromMoscow** [comment]
Are you sure that system_init does it? It should be atmel_start_init AFAIR.

**Comment by LeoZhang-ATMEL** [comment]
Yes, I can find them in atmel_start.c->atmel_start_init() at the newest content.

```
#include <atmel_start.h>

/**
 * Initializes MCU, drivers and middleware in the project
 **/
void atmel_start_init()
{
	system_init();
	temperature_sensors_init();
	stdio_redirect_init();
}
```

**Comment by hurricaneFromMoscow** [comment]
so, the main function should call atmel_start_init , not system_init as it does now.

**Comment by LeoZhang-ATMEL** [comment]
Yes, it it. Fixed.
Thanks.

**Pull request merged**
